let words = `関数,
             変数,
             定数,
             引数,
             クラス,
             インスタンス,
             レスポンス,
             配列,
             プロパティ,
             戻り値,
             インポート,
             エクスポート,
             宣言,
             サーバー,
             クライアント,
             ポスト,
             リクエスト,
             POP,
             マージ,
             ウェブアプリ,
             ネイティブアプリ,
             API,
             ライブラリ,
             コンパイル,
             コンパイラ言語,
             インタープリタ言語,
             手続き型,
             オブジェクト指向,
             AI,
             人工知能,
             強化学習,
             深層学習,
             ディープラーニング,
             教師あり学習,
             教師なし学習,
             センチメント分析,
             ウェブスクレイピング,
             webスクレイピング,
             WEBスクレイピング,
             Selenium,
             slenium,
             セレニウム,
             Pandas,
             pandas,
             BeautifulSoup,
             beautifulsoup,
             クラウド,
             IDE,
             統合開発環境,
             パッケージ,
             モジュール,
             メソッド,
             条件分岐,
             順次実行,
             反復,
             定期実行,
             localhost,
             ローカルホスト,
             localStorage,
             localstorage,
             ローカルストレージ,
             cookie,
             コンソール,
             ターミナル,
             文字列,
             ディレクトリ,
             フォルダ,
             ファイル,
             並列処理,
             並行処理,
             イベント,
             クラッキング,
             ブルートフォース,
             プロキシ,
             Tor,
             VPN,
             CORS,
             スタールシート,
             プラグイン,
             エディター,
             ハードウェア,
             ソフトウェア,
             アルゴリズム,
             リポジトリ,
             メインブランチ,
             検索エンジン,
             ウェブブラウザ,
             URL,
             URI,
             スキーム,
             ドメイン,
             パス,
             仮想通貨,
             暗号資産,
             ブロックチェーン,
             IoT,
             Ajax,
             非同期通信,
             テキストファイル,
             バイナリ,
             バイナリファイル,
             実行ファイル,
             .exe,
             .bin,
             .mp3,
             .mp4,
             .jpeg,
             .png,
             .htaccess,
             機械語,
             2進数,
             2進法,
             10進数,
             10進法,
             16進数,
             16進法,
             ヘッダー,
             フッター,
             パンくずリスト,
             拡張機能,
             ユーザースクリプト
             `;
words = words.replace(/\s/g, "").split(","); // 全ての空白を削除（改行も含めて）
let articles = document.getElementsByTagName("article");

function detectJargon() {
    for (let i = 0; i < articles.length; i++) {
        for (let word = 0; word < words.length; word++) {
            if (articles[i].textContent.includes(words[word])) {
                let original_text = new RegExp(String.raw `${words[word]}`, "g");
                let modified_text = `<jargon>
                                        <a href=https://e-words.jp/?q=${words[word]} target="_blank">${words[word]}</a>
                                     </jargon>`;
                articles[i].innerHTML = articles[i].innerHTML.replace(original_text, modified_text);
            }
        }
    }
}

export { detectJargon };